### ISSUE TITLE
升级到最新镜像后无法使用，报错“Blocking any further messages for 217493393 due to flood control”，重启无效

### ISSUE THREAD

**Issue by nageshuizeii** [Rongronggg9/RSS-to-Telegram-Bot#575] opened 2024-11-11 09:55 UTC
2024/11/11 17:52:21 | stderr | [33m2024-11-11-09:52:21:WARNING:RSStT.locks - Blocking any further messages for 217493393 due to flood control, 43838.00s left[0m
-- | -- | --
2024/11/11 17:52:21 | stderr | telethon.errors.rpcerrorlist.FloodWaitError: A wait of 43837 seconds is required (caused by SendMessageRequest)
2024/11/11 17:52:21 | stderr | raise errors.FloodWaitError(request=r, capture=diff)
2024/11/11 17:52:21 | stderr | File "/opt/venv/lib/python3.12/site-packages/telethon/client/users.py", line 56, in _call
2024/11/11 17:52:21 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/11 17:52:21 | stderr | return await self._call(self._sender, request, ordered=ordered)
2024/11/11 17:52:21 | stderr | File "/opt/venv/lib/python3.12/site-packages/telethon/client/users.py", line 30, in __call__
2024/11/11 17:52:21 | stderr | ^^^^^^^^^^^^^^^^^^^
2024/11/11 17:52:21 | stderr | result = await self(request)
2024/11/11 17:52:21 | stderr | File "/opt/venv/lib/python3.12/site-packages/telethon/client/messages.py", line 905, in send_message
2024/11/11 17:52:21 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/11 17:52:21 | stderr | return await self._client.send_message(
2024/11/11 17:52:21 | stderr | File "/opt/venv/lib/python3.12/site-packages/telethon/tl/custom/message.py", line 764, in respond
2024/11/11 17:52:21 | stderr | await (
2024/11/11 17:52:21 | stderr | File "/app/src/command/customization.py", line 334, in callback_get_activate_or_deactivate_page
2024/11/11 17:52:21 | stderr | await callback_get_activate_or_deactivate_page.__wrapped__(event, activate, lang=lang, chat_id=chat_id, page=1)
2024/11/11 17:52:21 | stderr | File "/app/src/command/customization.py", line 284, in cmd_activate_or_deactivate_subs
2024/11/11 17:52:21 | stderr | ^^^^^^^^^
2024/11/11 17:52:21 | stderr | return await fut
2024/11/11 17:52:21 | stderr | File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
2024/11/11 17:52:21 | stderr | await asyncio.wait_for(
2024/11/11 17:52:21 | stderr | File "/app/src/command/utils.py", line 368, in execute
2024/11/11 17:52:21 | stderr | await execute()
2024/11/11 17:52:21 | stderr | File "/app/src/command/utils.py", line 505, in wrapper
2024/11/11 17:52:21 | stderr | Traceback (most recent call last):
2024/11/11 17:52:21 | stderr | [31m2024-11-11-09:52:21:ERROR:RSStT.command - Uncaught error occurred when 那个水贼 (217493393) attempting to use /activate_subs[0m
2024/11/11 17:52:21 | stderr | [32m2024-11-11-09:52:21:INFO:RSStT.command - Allow 那个水贼 (217493393) to use /activate_subs[0m
2024/11/11 17:52:02 | stderr | [33m2024-11-11-09:52:02:WARNING:RSStT.locks - Blocking any further messages for -1002107268156 due to flood control, 43857.00s left[0m
2024/11/11 17:52:00 | stderr | [33m2024-11-11-09:52:00:WARNING:RSStT.locks - Blocking any further messages for 861035684 due to flood control, 43859.00s left[0m
2024/11/11 17:51:48 | stderr | [32m2024-11-11-09:51:48:INFO:RSStT.command - Allow 那个水贼 (217493393) to use /activate_subs[0m
2024/11/11 17:51:35 | stderr | CPU: 1 (usable) / 4 (available) / 4 (total)[0m
2024/11/11 17:51:35 | stderr | MULTIUSER: Enable
2024/11/11 17:51:35 | stderr | UVLOOP: Enable
2024/11/11 17:51:35 | stderr | TELEGRAPH: Enable (5 accounts)
2024/11/11 17:51:35 | stderr | DATABASE: sqlite:/app/config/db.sqlite3
2024/11/11 17:51:35 | stderr | R_PROXY (for RSS): not set
2024/11/11 17:51:35 | stderr | T_PROXY (for Telegram): not set
2024/11/11 17:51:35 | stderr | ERROR_LOGGING_CHAT: 217493393
2024/11/11 17:51:35 | stderr | MANAGER: 217493393
2024/11/11 17:51:35 | stderr | SELF: TG_to_rss @rsshubtg_bot (7269547590)
2024/11/11 17:51:35 | stderr | [32m2024-11-11-09:51:35:INFO:RSStT - RSS-to-Telegram-Bot (v2.9.0-47-g32709d5@dev, build@2024-11-07T16:28:12+00:00) started!

**Comment by Rongronggg9** [comment] 2024-11-11 16:27
Duplicate of #542

**Closed** 2024-11-11 16:28 UTC
