### ISSUE TITLE
Deploy on Railway from the fork dev branch, and hit NeedMemberInvalidError: The provided member is invalid or does not exist

### ISSUE THREAD

**Issue by ftx-class-action** [Rongronggg9/RSS-to-Telegram-Bot#227] opened 2022-12-28 03:54 UTC
Deploy on Railway from the fork dev branch, and hit an error
2022-12-28-03:15:21:WARNING:telethon.client.users - Telegram is having internal issues NeedMemberInvalidError: The provided member is invalid or does not exist (for example a thumb size) (caused by SetBotCommandsRequest)

**To Reproduce**
Follow the instruction on this link:
https://github.com/ftx-class-action/RSS-to-Telegram-Bot/blob/dev/docs/deployment-guide.md

got the token (##9:A##)from @BotFather 
got the user id (mine -> 1##2) from @userinfobot
got the api token (access_token: 67***12) from the url
Fork the repo
Deploy on Railway (dev branch)
when done, go the following error:
telethon.errors.rpcerrorlist.NeedMemberInvalidError: The provided member is invalid or does not exist (for example a thumb size) (caused by SetBotCommandsRequest)

I got the user Id from @userinfobot, and confirm my account info is correct, not sure why complained about member is invalid.  Should I turn off multiuser mode?

The fork was off the latest dev branch.

**Expected behavior**
no error, deployment successful

**Important log**
MANAGER: 1##2
T_PROXY (for Telegram): not set
R_PROXY (for RSS): not set
DATABASE: postgres
TELEGRAPH: Enable (1 accounts)
UVLOOP: Enable
MULTIUSER: Enable
CPU: 1 (usable) / 32 (available) / 32 (total)
2022-12-28-03:15:21:WARNING:telethon.client.users - Telegram is having internal issues NeedMemberInvalidError: The provided member is invalid or does not exist (for example a thumb size) (caused by SetBotCommandsRequest)
2022-12-28-03:15:23:WARNING:telethon.client.users - Telegram is having internal issues NeedMemberInvalidError: The provided member is invalid or does not exist (for example a thumb size) (caused by SetBotCommandsRequest)
2022-12-28-03:15:25:WARNING:telethon.client.users - Telegram is having internal issues NeedMemberInvalidError: The provided member is invalid or does not exist (for example a thumb size) (caused by SetBotCommandsRequest)
2022-12-28-03:15:27:WARNING:RSStT - Set command error: 
Traceback (most recent call last):
File "/app/src/__init__.py", line 256, in lazy
await asyncio.gather(*set_bot_commands_tasks)
File "/app/src/command/utils.py", line 661, in set_bot_commands
await env.bot(
File "/opt/venv/lib/python3.11/site-packages/telethon/client/users.py", line 30, in __call__
return await self._call(self._sender, request, ordered=ordered)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/venv/lib/python3.11/site-packages/telethon/client/users.py", line 129, in _call
raise last_error
File "/opt/venv/lib/python3.11/site-packages/telethon/client/users.py", line 84, in _call
result = await future
^^^^^^^^^^^^
telethon.errors.rpcerrorlist.NeedMemberInvalidError: The provided member is invalid or does not exist (for example a thumb size) (caused by SetBotCommandsRequest)

Showing 31 logs

Thank you in advance for your help!

**Comment by Rongronggg9** [comment] 2022-12-28 10:17
Duplicate of #216

**Closed** 2024-12-12 18:40 UTC
